development:
  tiramizoo_api_url: http://tiramizoo-beta.heroku.com/api/

test:
  tiramizoo_api_url: http://tiramizoo-beta.heroku.com/api/

production:
  tiramizoo_api_url: http://tiramizoo-beta.heroku.com/api/